### ISSUE TITLE
Config will fail if no sourcemap is available for a module

### ISSUE THREAD

**Issue by jbalsas** [ipeychev/lfr-module-config-generator#23]
Hey @ipeychev,

I think that after https://github.com/liferay/liferay-module-config-generator/blob/master/lib/config-generator.js#L548, the config process fails if the `*.map` file is not present. 

I'm guessing we could either:
- Check if the sourcemap file is present before updating it
- Have a property saying wether we want to udpate sourcemaps or not that we could pass to the command line

What do you think?

**Comment by ipeychev** [comment]
Hey Chema,

What crappy file is this with an URL to a source map, but without this source map? :D
This shouldn't happen on theory, but if the parsed file points to a non-existing map, then there is nothing to do - we will not update anything and return the current content.

Thanks,

**Comment by jbalsas** [comment]
Hahahaha... you're absolutely right :joy: 

It's just that as part of the build process, we weren't properly copying over the `*.map` files before running the config tool. I did update that already to make sure the maps were updated as well :)

Will close this, then :sweat_smile: 

Thanks!

**Comment by ipeychev** [comment]
:+1:
