### ISSUE TITLE
Non-idempotent over already analyzed sources

### ISSUE THREAD

**Issue by yuchi** [ipeychev/lfr-module-config-generator#24]
In a Liferay Module with a _package.json_ if you launch `gradle build` twice, without passing through a `clean` task, it will revert back to nameless defines.

This could be a problem with how tasks are run in Liferay.

/cc @Ithildir @jbalsas

---

For future reference you can solve this by forcing `clean` before `build` and `deploy`:

``` gradle
// build.gradle

build.mustRunAfter clean
build.dependsOn clean

deploy.mustRunAfter clean
deploy.dependsOn clean
```

**Comment by jbalsas** [comment]
Hey @yuchi, I think we already fixed this... which version are you running? Could you verify if https://issues.liferay.com/browse/LPS-68485 fixed this for you?

**Comment by yuchi** [comment]
Looks in fact the same issue. But it’s fixed in _com.liferay.gradle.plugins.workspace_ version `1.1.1` and the last public available version is `1.1.0` (which is the one we’re using now).

See: http://search.maven.org/#search|ga|1|com.liferay.gradle.plugins.workspace

**Comment by jbalsas** [comment]
Right... @ithildir should know more then

**Comment by yuchi** [comment]
In the worst case scenario I’ll make him fix by hand by patching the binaries in my workspace when @Ithildir will be in Milan :P

**Comment by Ithildir** [comment]
@yuchi, until we publish a new com.liferay.gradle.plugins.workspace, you can override the transitive dependency to `com.liferay.gradle.plugins` in your `settings.gradle` and use a more recent one:

``` gradle
dependencies {
        classpath group: "com.liferay", name: "com.liferay.gradle.plugins", version: "2.0.48"
        classpath group: "com.liferay", name: "com.liferay.gradle.plugins.workspace", version: "1.1.0"
    }
```

**Comment by yuchi** [comment]
@Ithildir I’m not that skilled on dependency management on Gradle. Does that setup override the one automatically included my _com.liferay.gradle.plugins.workspace_?

**Comment by Ithildir** [comment]
Yes, we're creating a resolution conflict with those 2 dependencies: Workspace wants to use 2.0.45, but you're telling Gradle you want 2.0.48 instead. And, [by default](https://docs.gradle.org/current/userguide/dependency_management.html#sub:version_conflicts), the newer version wins.

**Comment by yuchi** [comment]
Works flawlessly. Thanks for your clarity, as always.
