### ISSUE TITLE
Namespace define and require calls

### ISSUE THREAD

**Issue by jbalsas** [ipeychev/lfr-module-config-generator#25]
Liferay-AMD-Loader introduced a [namespace feature](https://github.com/liferay/liferay-amd-loader/issues/78). When enabled, Loader methods will be exposed as `[namespace].require` and `[namespace].define`.

Because of this, the scanned amd modules may be keeping a non-namespaced reference to it and won't be able to load it.

This is a request to add a `--namespace` feature to the `module-config-generator` which when present would rewrite any `define` and `require` calls to their namespaced versions.

**Comment by ipeychev** [comment]
Yeah, this has to be done and it shouldn't be very hard to do it. Do you need some help?

**Comment by jbalsas** [comment]
Yeah, I'll work on it with @julien

**Comment by julien** [comment]
Hi @jbalsas and @ipeychev,

Just making sure I understand correctly:  

+ If `--namespace` is passed and has the value `MyNamespace`; then `define` calls should become `MyNamespace.define`, is that correct? 

+ I assume, it also means that the original file should be overwritten? 
   And if so, do you have any pointers on how to test that.
  (Should a configuration generator rewrite your source files?)

+ What about the `require` calls, should that be done too? 
   Looking at the source I haven't found anything related to that.

Thanks

**Comment by jbalsas** [comment]
Hey @julien 
- Correct, if `--namespace My.Namespace` is passed both `define` and `require` calls should become `My.Namespace.define` and `My.Namespace.require`
- That's a fair point. In our case, this is governed by the `--skipFileOverride` flag. See https://github.com/liferay/liferay-module-config-generator/blob/master/lib/config-generator.js#L357 and https://github.com/liferay/liferay-module-config-generator/blob/master/lib/config-generator.js#L381 where we add the moduleName to the define calls. This should work in the same way, rewriting the files only if the flag is not set.

**Comment by julien** [comment]
Thanks @jbalsas 

However, I have an issue testing this, maybe you can see a solution: 

My input file looks like this.

```javascript
// file is `test/modal/js/namespace-define-override.es.js`

define("modal@2.0.0/js/namespace-define-override.es", ["exports"], function(exports) {
    var thing = {
        doStuff: function () {
            return 'doing stuff';
        }
    }
});
```

I added a new test to the existing test suite, similar to the existing ones, but with a change to the config generator's options:

```javascript
var configGenerator = new ConfigGenerator({
    args: [path.resolve(__dirname, 'modal')],
    config: '',
    filePattern: '**/namespace-define-override*.js',
    format: ['/_/g', '-'],
    ignorePath: false,
    moduleConfig: path.resolve(__dirname, 'modal/bower.json'),
    moduleRoot: path.resolve(__dirname, 'modal'),
    skipFileOverride: false, // We will re-write the file
    namespace: 'Liferay'
});
````

The first time the test runs, it finds the file, and is able to return/generate a configuration, but the next time the test runs, the original file has been *overwritten* and looks like this:

```javascript
// file is `test/modal/js/namespace-define-override.es.js`

Liferay.define("modal@2.0.0/js/namespace-define-override.es", ["exports"], function(exports) {
    var thing = {
        doStuff: function () {
            return 'doing stuff';
        }
    }
});
```

So the config generator doesn't find a  [match](https://github.com/liferay/liferay-module-config-generator/blob/master/lib/config-generator.js#L336) and doesn't generate the config. 

I'm not sure if it would be a good idea to modify the `match` according to the `namespace` option.
