### ISSUE TITLE
Is this module still relevant, having now the liferay-npm-bundler?

### ISSUE THREAD

**Issue by caneta** [ipeychev/lfr-module-config-generator#49]
One simple question: is this module still in use, after the creation of the [liferay-npm-bundler](https://github.com/liferay/liferay-npm-build-tools/tree/master/packages/liferay-npm-bundler)?
Thanks

**Comment by jbalsas** [comment]
Hey @caneta, we're working to discontinue this module, but right now it is still in use as older branches or developments won't necessarily need to migrate to the new bundler and will still need to generate the necessary loader information.

We don't plan to introduce new developments, and we'll move this into maintenance mode as soon as we've successfully migrated away all of our pieces.

Let us know if you have any other questions!
